default:
	gcc NetworkServoControl.c network.c openssc.c -o NetworkServoControl

broadcast:
	gcc NetworkBroadcast.c network.c -o NetworkBroadcast
	
listen:
	gcc NetworkListen.c network.c -o NetworkListen