default:
	gcc RoverNetworkServoControl.c RoverNetwork.c openssc.c -o RoverNetworkServoControl
	#gcc NetworkServoControl.c network.c openssc.c -o NetworkServoControl

broadcast:
	gcc RoverNetworkBroadcast.c RoverNetwork.c -o RoverNetworkBroadcast
	#gcc NetworkBroadcast.c network.c -o NetworkBroadcast
	
listen:
	gcc RoverNetworkListen.c RoverNetwork.c -o RoverNetworkListen
	#gcc NetworkListen.c network.c -o NetworkListen
